// <auto-generated />
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20240109082145_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DB.Models.Implementations.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Armor")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttacksPerRound")
                        .HasColumnType("integer");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Armor = 12,
                            AttackModifier = 9,
                            AttacksPerRound = 2,
                            Damage = "2d6",
                            DamageModifier = 5,
                            HitPoints = 42,
                            Name = "Bear"
                        },
                        new
                        {
                            Id = 2,
                            Armor = 13,
                            AttackModifier = 9,
                            AttacksPerRound = 1,
                            Damage = "1d12",
                            DamageModifier = 3,
                            HitPoints = 67,
                            Name = "Berserk"
                        },
                        new
                        {
                            Id = 3,
                            Armor = 20,
                            AttackModifier = 7,
                            AttacksPerRound = 2,
                            Damage = "1d8",
                            DamageModifier = 3,
                            HitPoints = 52,
                            Name = "Warrior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
